### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by notna1109** [izneo-get/lizzie-get#3]
Hello existerait-il un moyen de vous contacter par email merci

**Comment by izneo-get** [comment]
Vous pouvez laisser un message ici ou un lien vers un pastebin.

**Comment by notna1109** [comment]
En fait c'était pour avoir plus d'intimité et ne pas être lisible par n'importe qui.

**Comment by izneo-get** [comment]
J'ai bien compris, voila pourquoi je proposais un pastebin qui sera supprimable une fois lu. 

Je viens de me prendre un DMCA takedown, je n'ai pas particulièrement envie de mettre mon adresse email en clair.

**Comment by notna1109** [comment]
je comprends, comment faire via pastebin, je n'ai jamais utlisé

**Comment by izneo-get** [comment]
https://pastebin.com/
On écrit du texte, on valide et on récupère le lien qu'il nous donne.

**Comment by notna1109** [comment]
https://pastebin.com/FkDpDNUd

**Comment by izneo-get** [comment]
S'il est privé, seul vous pouvez le lire ;)

**Comment by notna1109** [comment]
https://pastebin.com/e7WvPNma

c'est mieux?
